name: Spring Boot Build and send to S3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4.4
      with:
          maven-version: 3.8.2
          
    - name: Build with Maven
      run: mvn clean install
      
    - name: Rename the artifact
      run: cp target/testdemo-0.0.1-SNAPSHOT.jar spring.jar
      
    - name: Upload to S3
      uses: hkusu/s3-upload-action@v2
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-northeast-1'
          aws-bucket: ${{ secrets.AWS_BUCKET }}
          #file-path: target/testdemo-0.0.1-SNAPSHOT.jar
          file-path: spring.jar
          destination-dir: '/build'
          output-file-url: 'true' # specify true
    - name: Show URL
      run: echo '${{ steps.upload.outputs.file-url }}' # use this output

  
