name: Spring Boot Build and send to S3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4.4
      with:
          maven-version: 3.8.2
          
    - name: Build with Maven
      run: mvn clean install
      
    - name: Upload to S3
      uses: hkusu/s3-upload-action@v2
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-northeast-1'
          aws-bucket: ${{ secrets.AWS_BUCKET }}
          file-path: '${{ github.workspace }}/target/*.jar'
          destination-dir: '/build'

  
